################
# apache2
################

# RUN set -e; \
#   rm -rf /var/www/html; \
#   mkdir -p /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html; \
#   chown -R www-data:www-data /var/lock/apache2 /var/run/apache2 /var/log/apache2 /var/www/html

COPY services/apache2 /package/airstack/apache2

RUN set -e; \
  mv /etc/apache2/apache2.conf /etc/apache2/apache2.conf.dist; \
  ln -sf /package/airstack/apache2/apache2.conf /etc/apache2/
