<%- "RUN echo 'deb http://http.debian.net/debian wheezy-backports main' >> /etc/apt/sources.list" if @config.build.from.distro.name is "wheezy" %>
USER root
ENV HOME /root
WORKDIR /root
RUN set -e; \
  groupadd --system airstack --gid 432; \
  useradd --uid 431 --system --base-dir /home --create-home --gid airstack --shell /bin/nologin --comment "airstack user" airstack; \
  chown -R airstack:airstack /home/airstack
