# COPY services/mysql /package/airstack/mysql
# VOLUME ["/var/lib/mysql"]

# ENV PATH $PATH:/usr/local/mysql/bin:/usr/local/mysql/scripts

# COPY docker-entrypoint.sh /entrypoint.sh
# ENTRYPOINT ["/entrypoint.sh"]
# CMD ["mysqld", "--datadir=/var/lib/mysql", "--user=mysql"]
